name: visionassist
description: Aplikasi Teknologi Bantu bagi Penyandang Gangguan Penglihatan

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Kamera
  camera: ^0.10.5+9

  # OCR - Google ML Kit
  google_mlkit_text_recognition: ^0.13.0

  # Text to Speech
  flutter_tts: ^4.0.2

  # Penyimpanan lokal
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0

  # Izin akses
  permission_handler: ^11.3.1

  # Image picker (untuk impor gambar)
  image_picker: ^0.8.9

  # File picker (untuk impor file PDF, Word, dll dari file manager)
  file_picker: ^8.1.4

  # Membaca isi PDF dan mengubah halaman jadi gambar untuk OCR
  syncfusion_flutter_pdf: ^27.1.58
  pdf_render_plus: ^1.4.16

  # Membaca isi file Word (.docx)
  docx_to_text: ^1.0.1

  # TFLite untuk YOLO
  tflite_flutter: 0.10.1

  # Konversi gambar kamera
  image: ^4.1.7

  # UI
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/yolov8n.tflite
    - assets/coco_labels.txt
